sudo: false
dist: trusty
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
install:
  - if [ -n "$GITHUB_OAUTH_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_OAUTH_TOKEN}; fi;
  - composer install --no-interaction
  # test app with symfony3 components in latest php
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer update && composer remove phpunit/phpunit --dev --no-interaction && composer require sebastian/phpcpd:~3.0 phpunit/phpunit:~5.7 && bin/suggested-tools.sh install; fi
  # Disable JIT compilation in hhvm, as the JIT is useless for short live scripts like tests.
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo 'hhvm.jit = 0' >> /etc/hhvm/php.ini; fi
  # For HHVM phpmetrics report isn't generated, try phpmetrics v2
  - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]] ; then composer update phpmetrics/phpmetrics; fi
script:
  - vendor/phpunit/phpunit/phpunit
  - ./phpqa tools
  - bin/ci.sh
#Â http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
